import { useEffect, useMemo, useRef, useState } from "react";
import { ArchiveBoxIcon, ArrowDownTrayIcon, BookOpenIcon, DocumentArrowUpIcon, DocumentIcon, ExclamationCircleIcon, MagnifyingGlassIcon, PencilSquareIcon, PlayIcon, PlusIcon, StopIcon, TrashIcon, XMarkIcon } from "@heroicons/react/24/outline";
import "./styles.css";

const KEYWORD_STORAGE = "keyword-scanner-keywords";
const API_BASE_URL = window.keywordScanner?.getApiBaseUrl?.() || "http://localhost:8000";
function fileType(name) { const ext = name.split(".").pop()?.toLowerCase(); return ["zip", "rar", "7z"].includes(ext) ? "ZIP" : ext === "pdf" ? "PDF" : ["doc", "docx"].includes(ext) ? "Word" : ["xls", "xlsx"].includes(ext) ? "Excel" : ["ppt", "pptx"].includes(ext) ? "PowerPoint" : "Text"; }
function TypeBadge({ type }) { return <span className={`type-badge ${type.toLowerCase().replace(" ", "-")}`}>{type === "PowerPoint" ? "P" : type === "Excel" ? "X" : type === "Word" ? "W" : type === "PDF" ? "PDF" : type === "ZIP" ? "ZIP" : "TXT"}</span>; }
function highlight(text, keyword) { const parts = text.split(keyword); return <>{parts.map((part, index) => <span key={`${part}-${index}`}>{part}{index < parts.length - 1 && <mark>{keyword}</mark>}</span>)}</>; }
function storedKeywords() { try { return JSON.parse(localStorage.getItem(KEYWORD_STORAGE) || "[]"); } catch { return []; } }

export function App() {
  const fileInputRef = useRef(null); const markdownInputRef = useRef(null); const scanControllerRef = useRef(null); const scanIdRef = useRef(null); const progressTimerRef = useRef(null);
  const [files, setFiles] = useState([]); const [keywords, setKeywords] = useState(storedKeywords); const [showLibrary, setShowLibrary] = useState(false); const [draft, setDraft] = useState(""); const [results, setResults] = useState([]); const [scanned, setScanned] = useState(false); const [scanning, setScanning] = useState(false); const [dragging, setDragging] = useState(false); const [notice, setNotice] = useState(""); const [progress, setProgress] = useState({ value: 0, elapsed: 0 });
  const hitFiles = useMemo(() => results.length, [results]);
  useEffect(() => localStorage.setItem(KEYWORD_STORAGE, JSON.stringify(keywords)), [keywords]);
  function addFiles(list) { const next = Array.from(list || []).map((file) => ({ id: crypto.randomUUID(), name: file.name, size: `${Math.max(1, Math.round(file.size / 1024))} KB`, type: fileType(file.name), raw: file })); if (next.length) { setFiles((current) => [...current, ...next]); setResults([]); setScanned(false); } }
  function removeFile(id) { setFiles((current) => current.filter((file) => file.id !== id)); setResults([]); setScanned(false); }
  function addKeyword() { const value = draft.trim(); if (value && !keywords.includes(value)) setKeywords((current) => [...current, value]); setDraft(""); }
  async function importMarkdown(event) { const markdownFile = event.target.files?.[0]; event.target.value = ""; if (!markdownFile) return; const words = (await markdownFile.text()).split(/\r?\n/).map((line) => line.replace(/^\s*[-*+]\s+/, "").trim()).filter((line) => line && !line.startsWith("#") && !line.startsWith(">")); const unique = [...new Set(words)]; setKeywords((current) => [...new Set([...current, ...unique])]); setNotice(`已从 ${markdownFile.name} 导入 ${unique.length} 个关键词`); }
  function exportMarkdown() { const content = `# 关键词词库\n\n> 每行一个关键词，可编辑后重新导入。\n\n${keywords.map((word) => `- ${word}`).join("\n")}\n`; const url = URL.createObjectURL(new Blob([content], { type: "text/markdown;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "关键词词库.md"; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
  function clearProgress() { if (progressTimerRef.current) window.clearInterval(progressTimerRef.current); progressTimerRef.current = null; }
  function beginProgress() { setProgress({ value: 6, elapsed: 0 }); progressTimerRef.current = window.setInterval(() => setProgress((current) => ({ elapsed: current.elapsed + 1, value: Math.min(92, current.value + (current.value < 55 ? 5 : 1)) })), 1000); }
  async function stopScan() { const scanId = scanIdRef.current; scanControllerRef.current?.abort(); clearProgress(); scanIdRef.current = null; setScanning(false); setNotice("检测已停止。已完成的结果不会显示，请重新开始检测。"); if (scanId) await fetch(`${API_BASE_URL}/api/scan/${scanId}/cancel`, { method: "POST" }).catch(() => undefined); }
  async function scan() { setNotice(""); setResults([]); setScanned(false); if (!files.length) { setNotice("请先导入至少一份文件。"); return; } if (!keywords.length) { setNotice("词库为空，请先添加关键词或导入 Markdown 词库。"); return; } const controller = new AbortController(); const scanId = crypto.randomUUID(); scanControllerRef.current = controller; scanIdRef.current = scanId; setScanning(true); beginProgress(); try { const body = new FormData(); files.forEach((file) => body.append("files", file.raw)); const response = await fetch(`${API_BASE_URL}/api/scan?scan_id=${scanId}&keywords=${encodeURIComponent(keywords.join(","))}`, { method: "POST", body, signal: controller.signal }); if (!response.ok) throw new Error(await response.text()); const hits = await response.json(); if (scanIdRef.current !== scanId) return; const grouped = Object.values(hits.reduce((all, hit) => { const current = all[hit.file] || { file: hit.file, type: fileType(hit.file), count: 0, hits: [] }; current.count += 1; const position = hit.sheet ? `${hit.sheet} · 第 ${hit.row} 行 · 第 ${hit.column} 列` : `第 ${hit.page || 1} 页 · 第 ${hit.paragraph || 1} 段`; current.hits.push([hit.keyword, hit.sentence, position]); all[hit.file] = current; return all; }, {})); setResults(grouped); setScanned(true); setProgress((current) => ({ ...current, value: 100 })); } catch (error) { if (scanIdRef.current === scanId) setNotice(error.name === "AbortError" ? "检测已停止。" : `扫描未完成：${error.message || "请确认本地后端已启动"}`); } finally { if (scanIdRef.current === scanId) { clearProgress(); scanControllerRef.current = null; scanIdRef.current = null; setScanning(false); } } }
  const summary = scanned ? <><b>已扫描 {files.length} 份文件，<em>{hitFiles} 份</em>出现关键词</b><span>{hitFiles ? "已按词库匹配并保留命中位置" : "未发现词库中的关键词"}</span></> : <><b>{notice || "等待导入文件与关键词词库"}</b><span>{notice ? "请处理后再开始检测" : "文件与词库为空时不会产生任何告警"}</span></>;
  return <main className="app-shell">
    <aside className="left-rail"><div className="brand"><span className="brand-mark"><MagnifyingGlassIcon /></span><span>关键词检索器</span></div><section className="upload-section"><h2>导入文件</h2><div className={`drop-zone ${dragging ? "is-dragging" : ""}`} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); addFiles(event.dataTransfer.files); }}><div className="upload-art"><DocumentIcon /><ArchiveBoxIcon /></div><strong>拖拽文件或压缩包至此</strong><span>或点击导入</span><button className="secondary-button" onClick={() => fileInputRef.current?.click()}><DocumentArrowUpIcon />导入文件</button><input ref={fileInputRef} type="file" multiple hidden onChange={(event) => addFiles(event.target.files)} accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.zip,.rar,.7z" /></div></section><section className="file-list-section"><div className="section-title">已导入文件 <span>({files.length})</span></div><div className="file-list">{files.length ? files.map((file) => <div className="file-row" key={file.id}><TypeBadge type={file.type} /><div><b>{file.name}</b><small>{file.size} · 已就绪</small></div><button className="remove-file" onClick={() => removeFile(file.id)} aria-label={`删除 ${file.name}`}><XMarkIcon /></button></div>) : <div className="empty-file-list">尚未导入文件</div>}</div></section><button className="library-button" onClick={() => setShowLibrary(true)}><BookOpenIcon />关键词词库 <span>{keywords.length}</span></button></aside>
    <section className="workspace"><header className="workspace-header"><h1>检测中心</h1><div className="scan-actions"><button className="scan-button" onClick={scan} disabled={scanning}><PlayIcon />开始检测</button>{scanning && <button className="stop-button" onClick={stopScan}><StopIcon />停止检测</button>}</div></header><div className={`summary ${scanned ? "visible" : "neutral"}`}><ExclamationCircleIcon /><div>{summary}</div>{scanning && <div className="progress-wrap"><div className="progress-meta"><span>正在处理 {files.length} 份文件</span><span>已用时 {progress.elapsed} 秒</span></div><div className="progress-track"><i style={{ width: `${progress.value}%` }} /></div></div>}</div><section className="results-section"><div className="results-heading"><div><h2>命中结果</h2><span>仅显示包含关键词的文件，更多命中内容可向下滚动查看</span></div><span className="status-dot">{scanning ? "正在扫描" : scanned ? "检测完成" : "等待检测"}</span></div><div className="result-scroll">{results.map((group) => <article className="result-card" key={group.file}><header><ExclamationCircleIcon className="alert-icon" /><TypeBadge type={group.type} /><b>{group.file}</b><span className="match-count">命中 {group.count} 个关键词</span><div className="tags">{[...new Set(group.hits.map(([word]) => word))].map((word) => <span key={word}>{word}</span>)}</div></header><div className="hit-lines">{group.hits.map(([word, text, position], index) => <div className="hit-line" key={`${word}-${position}-${index}`}><span className="bullet">•</span><p>{highlight(text, word)}</p><span className="position">{position}</span></div>)}</div></article>)}{!results.length && <div className="empty-results">{scanned ? "未发现词库中的关键词。" : "检测后，命中关键词的文件会显示在这里。"}</div>}</div></section></section>
    {showLibrary && <div className="modal-backdrop" onMouseDown={() => setShowLibrary(false)}><section className="keyword-modal" onMouseDown={(event) => event.stopPropagation()}><header><div><span className="eyebrow">KEYWORD LIBRARY</span><h2>关键词词库</h2><p>词库会自动保存在当前浏览器中；Markdown 文件每行一个关键词。</p></div><button className="icon-button" onClick={() => setShowLibrary(false)}><XMarkIcon /></button></header><div className="keyword-editor"><input value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => event.key === "Enter" && addKeyword()} placeholder="输入新关键词" /><button onClick={addKeyword}><PlusIcon />添加</button></div><div className="library-tools"><button onClick={() => markdownInputRef.current?.click()}><DocumentArrowUpIcon />导入 Markdown</button><button onClick={exportMarkdown}><ArrowDownTrayIcon />导出 Markdown</button><input ref={markdownInputRef} type="file" hidden accept=".md,text/markdown,text/plain" onChange={importMarkdown} /></div><div className="keyword-list">{keywords.length ? keywords.map((word) => <div key={word}><span>{word}</span><button onClick={() => { const value = window.prompt("修改关键词", word); if (value?.trim()) setKeywords((all) => [...new Set(all.map((item) => item === word ? value.trim() : item))]); }} aria-label={`修改 ${word}`}><PencilSquareIcon /></button><button onClick={() => setKeywords((all) => all.filter((item) => item !== word))} aria-label={`删除 ${word}`}><TrashIcon /></button></div>) : <div className="empty-keywords">词库为空。添加关键词或导入 Markdown 文件开始检测。</div>}</div><footer><span>共 {keywords.length} 个关键词</span><button onClick={() => setShowLibrary(false)}>完成</button></footer></section></div>}
  </main>;
}
